import pandas as pd

# Create the checklist as a DataFrame
data = {
    "Spec Topic": [
        "Qur’an as revelation, structure, use",
        "Hadith / Sunna / authority",
        "Sources of Shari’a: Qiyas, Ijma",
        "Importance of Shari’a in society",
        "Understandings of Jihad",
        "Criticisms of sources (authenticity, reform)",
        "Core beliefs (Tawhid, Prophethood, etc.)",
        "Five Pillars and practices",
        "Festivals and rites of passage",
        "Ethical norms in daily life (halal, haram)",
        "Ummah / Community / Identity",
        "Diversity within Islam",
        "Islam and change (modernisation, reform)",
        "Crime & punishment ethics (scholars)",
        "Islamic state, secularisation debate",
        "Science vs Islam (origins, evolution)",
        "Pluralism and Islamic responses",
        "Family life in Islam",
        "Islam and migration (UK context)",
        "Western perceptions of Islam",
        "New scholars (Ahmed An-Na’im, Naima Asif)",
        "Contemporary case studies (UK/worldwide)",
        "Evaluation & AO2 skills",
        "Bridging AS to A2 topics"
    ],
    "Covered in Gray (AS)": [
        "✔", 
        "✔", 
        "", 
        "", 
        "", 
        "✔ (intro)", 
        "✔", 
        "✔", 
        "✔", 
        "✔", 
        "✔", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "✔ (some)", 
        "✔", 
        "✘ (requires linking)"
    ],
    
    "Covered in Morar (A2)": [
        "✔ (via Shari’a)", 
        "✔ (via Shari’a)", 
        "✔", 
        "✔", 
        "✔", 
        "✔", 
        "", 
        "", 
        "", 
        "", 
        "✔ (identity & change)", 
        "✔", 
        "✔", 
        "✔",
        "✔", 
        "✔", 
        "✔", 
        "✔", 
        "✔", 
        "✔", 
        "⚠ check edition", 
        "✔ (some)", 
        "✔", 
        "✘ (you link it)"
    ],

    "Needs Supplement?": [
        "", 
        "", 
        "", 
        "", 
        "", 
        "Maybe (depth)", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "", 
        "Maybe (examples)", 
        "Maybe (science link)", 
        "", 
        "", 
        "Yes (UK-specific)", 
        "Yes (examples)", 
        "Yes if not latest ed.", 
        "Yes (recent)", 
        "Yes (model essays)", 
        "Yes (lesson design)"
    ]
}

df = pd.DataFrame(data)

# Save to Excel
df.to_excel("Islam_A_Level_Spec_Checklist.xlsx", index=False)