#2) Printing Shapes:
print("2.MAKING A RIGHT-ANGLE TRIANGLE")
print("    /|")
print("   / |")
print("  /  |")
print(" /___|")
print("++++++++++++++++++++++++++++++++++++\n")
print("-----------------------------------¦")
print("Extra Shapes                       ¦")
print("-----------------------------------¦")
print("1.Here is a Square                 ¦")
print("|-----|                            ¦")
print("|     |                            ¦")
print("|_____|                            ¦")
print("-----------------------------------¦")
print("2.Here is a Rectangle              ¦")
print("|-----|                            ¦")
print("|     |                            ¦")
print("|     |                            ¦")
print("|     |                            ¦")
print("|_____|                            ¦")
print("-----------------------------------¦")
